AS_WORKDIR = renameLocalDir(cfg.AS)

AS_index_input,AS_graph_file,AS_index_output = moduleInputOutput("aberrant-splicing-pipeline",AS_WORKDIR,cfg.AS)

rule aberrantSplicing:
    input: AS_index_input, AS_graph_file
    output: AS_index_output
    run:
        if cfg.AS.run:
            ci(str(AS_WORKDIR), 'aberrant-splicing-pipeline')

rule aberrantSplicing_dependency:
    output: AS_graph_file

    shell: "snakemake --nolock --rulegraph {AS_index_output} | dot -Tsvg -Grankdir=TB > {output}"

