AS_WORKDIR = cfg.AS.getWorkdir(str_=False)

AS_index_name = "aberrant-splicing-pipeline"
AS_index_input, AS_index_output, AS_graph_file, _ = createIndexRule(
    scriptsPath=str(AS_WORKDIR),
    index_name=AS_index_name
)

rule aberrantSplicing:
    input: AS_index_input, AS_graph_file
    output: AS_index_output
    run: ci(str(AS_WORKDIR), AS_index_name)

rule aberrantSplicing_dependency:
    output: AS_graph_file
    shell: "snakemake --rulegraph {AS_index_output} | dot -Tsvg -Grankdir=TB > {output}"